var value = 100;

d3.select("#container")
	.append("svg")
		.attr("width", 1000)
		.attr("height", 600)
		.attr("id", "canvas")
	.append("rect")
		.attr("x", value)
		.attr("y", value)
		.attr("width", 400)
		.attr("height", 200)
		.style("fill", "#d35400")
	d3.select("svg")
		.append("circle")
		.attr("cx", 300)
		.attr("cy", value)
		.attr("r", 50)
		.style("fill", "#2980b9")